#:schema node_modules/wrangler/config-schema.json
name = "indexer"
main = "src/index.ts"
compatibility_date = "2024-10-22"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true
head_sampling_rate = 1 # optional. default = 1.

[triggers]
crons = ["*/10 * * * *"] # Run every 10 min

[[workflows]]
name = "indexer"
binding = "INDEXING_WORKFLOW"
class_name = "IndexingWorkflow"

[[d1_databases]]
binding = "DATABASE"
database_name = "index_db"
database_id = "401697db-2b00-4d5e-a77d-5d6225bf9b98"